version: "3.9"

services:
  mariadb:
    image: mariadb:11
    restart: always
    env_file:
      - .env.db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    env_file:
      - .env.cloudflare
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - app-network
    depends_on:
      - web
volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
